apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: postgresql-secret
  labels:
    name: postgresql-secret
    app: ansible-awx
    app-component: ansible-awx-postgresql-secret
stringData:
  database-name: sampledb
  database-password: postgre_password
  database-admin-password: postgre_password
  database-user: postgre_user
