---
apiVersion: v1
kind: Secret
metadata:
  name:  ansible-awx-secrets
  labels:
    app: ansible-awx
    app-component: ansible-awx-secrets
type: Opaque
data:
  admin_password: "YWRtaW5fcGFzc3dvcmQ="
  pg_password: "cG9zdGdyZV9wYXNzd29yZA=="
  rabbitmq_password: "cmFiYml0X3Bhc3N3b3Jk"
  rabbitmq_erlang_cookie: "SE9TUElURUNDT09LSUVZRUFI"
  #credentials.py base64 encoded
  confd_contents: REFUQUJBU0VTID0gewogICAgJ2RlZmF1bHQnOiB7CiAgICAgICAgJ0FUT01JQ19SRVFVRVNUUyc6IFRydWUsCiAgICAgICAgJ0VOR0lORSc6ICdkamFuZ28uZGIuYmFja2VuZHMucG9zdGdyZXNxbCcsCiAgICAgICAgJ05BTUUnOiAic2FtcGxlZGIiLAogICAgICAgICdVU0VSJzogInBvc3RncmVfdXNlciIsCiAgICAgICAgJ1BBU1NXT1JEJzogInBvc3RncmVfcGFzc3dvcmQiLAogICAgICAgICdIT1NUJzogInBvc3RncmVzcWwiLAogICAgICAgICdQT1JUJzogIjU0MzIiLAogICAgfQp9CkJST0tFUl9VUkwgPSAnYW1xcDovL3t9Ont9QHt9Ont9L3t9Jy5mb3JtYXQoCiAgICAiYXd4IiwKICAgICJyYWJiaXRfcGFzc3dvcmQiLAogICAgImxvY2FsaG9zdCIsCiAgICAiNTY3MiIsCiAgICAiYXd4IikKQ0hBTk5FTF9MQVlFUlMgPSB7CiAgICAnZGVmYXVsdCc6IHsnQkFDS0VORCc6ICdhc2dpX2FtcXAuQU1RUENoYW5uZWxMYXllcicsCiAgICAgICAgICAgICAgICAnUk9VVElORyc6ICdhd3gubWFpbi5yb3V0aW5nLmNoYW5uZWxfcm91dGluZycsCiAgICAgICAgICAgICAgICAnQ09ORklHJzogeyd1cmwnOiBCUk9LRVJfVVJMfX0KfQo=
