version: '3'
services:
  api:
    image: 'alpine'
    environment:
     - NODE_ENV=production
     - TEST_VAR=${MY_TEST_VAR}
     - LANG
     - MOST_IMPORTANT_KEY
     - FORCE
    # There's no «sleep infinity» in alpine's sleep ;)
    entrypoint: sleep 1000
