apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-rolling
  name: nginx-rolling
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-rolling
  sessionAffinity: None
  type: NodePort
